
name: Build and Package Chainweb Snapshots tool
inputs:
  version:
    required: true
  os-version:
    required: true
  pkg-release:
    required: true

runs:
  using: composite

  steps:
    - name: Install NFPM
      uses: ./actions/nfpm_install

    - name: Build Debian package
      working-directory: ${{ github.action_path }}
      env:
        VERSION: "${{ inputs.version }}"
        RELEASE: ${{ inputs.pkg-release }}
      shell: bash
      run: |
        nfpm package -p deb -f nfpm.yaml \
          -t ${GITHUB_WORKSPACE}/dist/chainweb-snapshots_${{ inputs.version }}-${{ inputs.os-version }}_amd64.deb
