
name: Build and Package Chainweb Mining client

inputs:
  tag:
    required: true
  ghc:
    required: true
  cabal:
    required: true
  version:
    required: true
  os-version:
    required: true
  pkg-release:
    required: true

runs:
  using: composite

  steps:
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
          repository: kda-community/chainweb-mining-client.git
          ref: ${{ inputs.tag }}
          path: chainweb-mining-client

    - name: Install NFPM
      uses: ./actions/nfpm_install

    - name: Set permissions for .ghcup (ubuntu)
      shell: bash
      run: sudo chown -R $USER /usr/local/.ghcup

    - name: Install GHC and Cabal
      uses: haskell-actions/setup@v2
      with:
         ghc-version: ${{ inputs.ghc }}
         cabal-version: ${{ inputs.cabal }}

    - name: Update package database
      shell: bash
      run: cabal update

    - name: Setting up MPFR (Ubuntu)
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y libmpfr-dev

    - name: Create cabal.project.local
      working-directory: ./chainweb-mining-client
      shell: bash
      run: |
        cat > cabal.project.local <<EOF
        documentation: False
        package pact
          tests: False
          benchmarks: False
          documentation: False
          optimization: 1

        EOF

    - name: Build with Cabal
      uses: ./actions/cabal_std_build
      with:
        src_dir: ${{ github.action_path }}/chainweb-mining-client
        dst_dir: ${{ github.action_path }}
        exe: chainweb-mining-client

    - name: Copy and prepare materials
      working-directory: ${{ github.action_path }}
      shell: bash
      run: |
        strip chainweb-mining-client
        cp chainweb-mining-client/README.md .

    - name: Check version
      working-directory: ${{ github.action_path }}
      shell: bash
      run: |
        OUTPUT=$(./chainweb-mining-client --version)
        VERSION=$(echo "$OUTPUT" | sed -n 's/.*chainweb-mining-client-\([^ ]*\) .*/\1/p')
        if [[ "$VERSION" != "${{ inputs.version }}" ]]; then
          echo "Version mismatch: expected ${{ inputs.version }}, got $VERSION"
          exit 1
        fi

    - name: Gen base config file
      working-directory: ${{ github.action_path }}
      shell: bash
      run: |
        mkdir -p config
        ./chainweb-mining-client \
          --public-key 0000000000000000000000000000000000000000000000000000000000000000 \
          --node 127.0.0.1:1848 \
          --stratum-port 1917 \
          --print-config > config/config.yaml

    - name: Build Deb file
      working-directory: ${{ github.action_path }}
      env:
        VERSION: ${{ inputs.version }}
        RELEASE: ${{ inputs.pkg-release }}-${{ inputs.os-version }}
      shell: bash
      run: |
        nfpm package -p deb -f nfpm.yaml \
          -t ${GITHUB_WORKSPACE}/dist/chainweb-mining-client_${{ inputs.version }}-${{ inputs.os-version }}_amd64.deb