
name: Install NFPM

inputs:
  version:
    required: false
    default: "2.47.0"

runs:
  - name: Install NFPM
    env:
      NFPM_VERSION: ${{ inputs.version }}
      shell: bash
      run: |
        wget -q https://github.com/goreleaser/nfpm/releases/download/v${NFPM_VERSION}/nfpm_${NFPM_VERSION}_amd64.deb
        sudo dpkg -i nfpm_${NFPM_VERSION}_amd64.deb
