
name: Build packages and Deb repository

on:
  workflow_dispatch:

  push:

jobs:
  build_deb:
    strategy:
      fail-fast: false
      matrix:
        os-version:
          - bookworm
          - trixie
          - jammy
          - noble
          - resolute

        package:
          - name: kda-tool
            version: "1.2"
            tag: "1.2"
            ghc: 9.10.3
            cabal: "3.12"
            build-dir: kda-tool-1

        include:
          - os-version: bookworm
            runner: ubuntu-22.04
          - os-version: trixie
            runner: ubuntu-24.04
          - os-version: jammy
            runner: ubuntu-22.04
          - os-version: noble
            runner: ubuntu-24.04
          - os-version: resolute
            runner: ubuntu-24.04

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Prepare directories
        run: |
          cp -rf packages/${{ matrix.package.build-dir }} current
          mkdir -p dist

      - name: Build package
        uses: ./current
        with:
          tag: ${{ matrix.package.tag }}
          version: ${{ matrix.package.version }}
          ghc: ${{ matrix.package.ghc }}
          cabal: ${{ matrix.package.cabal }}

      - name: List packages
        run : ls -alh dist

      - name: Upload Deb packages
        uses: actions/upload-artifact@v7
        with:
          name: deb-${{ matrix.package.name }}-deb-${{ matrix.package.version }}-${{ matrix.os-version }}
          path: dist/*.deb